[phases.setup]
nixPkgs = ["...", "dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd ScanPlantAPI/ScanPlantAPI",
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "cd ScanPlantAPI/ScanPlantAPI/out && dotnet ScanPlantAPI.dll --urls http://0.0.0.0:$PORT"
